/*
 * Auto generated by code_generator
 * Please do not modify it.
 */
package client

import (
	//"github.com/astaxie/beego"
	"github.com/golang/protobuf/proto"
	"showgirl/models/utils"
)

type AccountClient struct {
	CommonClient
}


func (this *AccountClient) ThirdPartyWXLogin(hdr *STUserTrustInfo, req *STThirdPartyWXLoginReq, header map[string]string) (*STRspHeader, *STThirdPartyWXLoginRsp, error) {

	utils.Debug(hdr.GetFlowId(), "AccountClient ThirdPartyWXLogin Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Account", "/Account/ThirdPartyWXLogin", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Account ThirdPartyWXLogin bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STThirdPartyWXLoginRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "AccountClient ThirdPartyWXLogin Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *AccountClient) GetMyInfo(hdr *STUserTrustInfo, req *STGetMyInfoReq, header map[string]string) (*STRspHeader, *STGetMyInfoRsp, error) {

	utils.Debug(hdr.GetFlowId(), "AccountClient GetMyInfo Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Account", "/Account/GetMyInfo", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Account GetMyInfo bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STGetMyInfoRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "AccountClient GetMyInfo Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

