// Code generated by protoc-gen-go. DO NOT EDIT.
// source: AccountSvr.proto

/*
Package client is a generated protocol buffer package.

It is generated from these files:
	AccountSvr.proto
	CommonProtocol.proto
	PaySvr.proto
	RecommendSvr.proto

It has these top-level messages:
	STThirdPartyWXLoginReq
	STThirdPartyWXLoginRsp
	STGetMyInfoReq
	STGetMyInfoRsp
	STUserTrustInfo
	STCookieInfo
	STRspHeader
	CommonReq
	CommonRsp
	CommonClientRsp
	STCreateTransactionReq
	STCreateTransactionRsp
	STImageListInfo
	STQueryRecommendListReq
	STQueryRecommendListRsp
	STStyleImageListReq
	STStyleImageListRsp
*/
package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 微信登录
type STThirdPartyWXLoginReq struct {
	Code             *string `protobuf:"bytes,1,req,name=code" json:"code,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STThirdPartyWXLoginReq) Reset()                    { *m = STThirdPartyWXLoginReq{} }
func (m *STThirdPartyWXLoginReq) String() string            { return proto.CompactTextString(m) }
func (*STThirdPartyWXLoginReq) ProtoMessage()               {}
func (*STThirdPartyWXLoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *STThirdPartyWXLoginReq) GetCode() string {
	if m != nil && m.Code != nil {
		return *m.Code
	}
	return ""
}

type STThirdPartyWXLoginRsp struct {
	UserKey          *string `protobuf:"bytes,1,req,name=UserKey" json:"UserKey,omitempty"`
	UserId           *string `protobuf:"bytes,2,opt,name=UserId" json:"UserId,omitempty"`
	NickName         *string `protobuf:"bytes,3,opt,name=NickName" json:"NickName,omitempty"`
	Url              *string `protobuf:"bytes,4,opt,name=Url" json:"Url,omitempty"`
	LastTime         *int64  `protobuf:"zigzag64,5,opt,name=LastTime" json:"LastTime,omitempty"`
	ChargeNum        *int32  `protobuf:"zigzag32,6,opt,name=ChargeNum" json:"ChargeNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STThirdPartyWXLoginRsp) Reset()                    { *m = STThirdPartyWXLoginRsp{} }
func (m *STThirdPartyWXLoginRsp) String() string            { return proto.CompactTextString(m) }
func (*STThirdPartyWXLoginRsp) ProtoMessage()               {}
func (*STThirdPartyWXLoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *STThirdPartyWXLoginRsp) GetUserKey() string {
	if m != nil && m.UserKey != nil {
		return *m.UserKey
	}
	return ""
}

func (m *STThirdPartyWXLoginRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *STThirdPartyWXLoginRsp) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *STThirdPartyWXLoginRsp) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *STThirdPartyWXLoginRsp) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

func (m *STThirdPartyWXLoginRsp) GetChargeNum() int32 {
	if m != nil && m.ChargeNum != nil {
		return *m.ChargeNum
	}
	return 0
}

// 获取自己的信息
type STGetMyInfoReq struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STGetMyInfoReq) Reset()                    { *m = STGetMyInfoReq{} }
func (m *STGetMyInfoReq) String() string            { return proto.CompactTextString(m) }
func (*STGetMyInfoReq) ProtoMessage()               {}
func (*STGetMyInfoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type STGetMyInfoRsp struct {
	UserId           *string `protobuf:"bytes,1,opt,name=UserId" json:"UserId,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=NickName" json:"NickName,omitempty"`
	Url              *string `protobuf:"bytes,3,opt,name=Url" json:"Url,omitempty"`
	LastTime         *int64  `protobuf:"zigzag64,4,opt,name=LastTime" json:"LastTime,omitempty"`
	ChargeNum        *int32  `protobuf:"zigzag32,5,opt,name=ChargeNum" json:"ChargeNum,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STGetMyInfoRsp) Reset()                    { *m = STGetMyInfoRsp{} }
func (m *STGetMyInfoRsp) String() string            { return proto.CompactTextString(m) }
func (*STGetMyInfoRsp) ProtoMessage()               {}
func (*STGetMyInfoRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *STGetMyInfoRsp) GetUserId() string {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return ""
}

func (m *STGetMyInfoRsp) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *STGetMyInfoRsp) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

func (m *STGetMyInfoRsp) GetLastTime() int64 {
	if m != nil && m.LastTime != nil {
		return *m.LastTime
	}
	return 0
}

func (m *STGetMyInfoRsp) GetChargeNum() int32 {
	if m != nil && m.ChargeNum != nil {
		return *m.ChargeNum
	}
	return 0
}

func init() {
	proto.RegisterType((*STThirdPartyWXLoginReq)(nil), "client.STThirdPartyWXLoginReq")
	proto.RegisterType((*STThirdPartyWXLoginRsp)(nil), "client.STThirdPartyWXLoginRsp")
	proto.RegisterType((*STGetMyInfoReq)(nil), "client.STGetMyInfoReq")
	proto.RegisterType((*STGetMyInfoRsp)(nil), "client.STGetMyInfoRsp")
}

func init() { proto.RegisterFile("AccountSvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xce, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x71, 0xd2, 0xd6, 0x6a, 0x9f, 0x32, 0xdb, 0x1c, 0x24, 0xc7, 0xd2, 0x83, 0xe4, 0xe4,
	0xff, 0x20, 0x1e, 0x64, 0x38, 0x8b, 0xac, 0x19, 0x7a, 0x0d, 0xc9, 0x73, 0x0b, 0xae, 0x49, 0x97,
	0x64, 0x42, 0x0f, 0xfe, 0xef, 0x32, 0x45, 0x98, 0x74, 0xd7, 0xef, 0xfb, 0xc1, 0xe7, 0x41, 0x79,
	0xaf, 0x94, 0xdb, 0xdb, 0xd8, 0x7d, 0xfa, 0xbb, 0xc1, 0xbb, 0xe8, 0x68, 0xae, 0xb6, 0x06, 0x6d,
	0x6c, 0x6e, 0xe1, 0xa6, 0x13, 0x62, 0x63, 0xbc, 0x7e, 0x91, 0x3e, 0x8e, 0xaf, 0x6f, 0x0b, 0xb7,
	0x36, 0x76, 0x89, 0x3b, 0x7a, 0x05, 0x99, 0x72, 0x1a, 0x19, 0xa9, 0x13, 0x5e, 0x34, 0x5f, 0xa7,
	0x77, 0x61, 0xa0, 0xd7, 0x70, 0xbe, 0x0a, 0xe8, 0x9f, 0x70, 0xfc, 0x9d, 0xd2, 0x19, 0xe4, 0x87,
	0x30, 0xd7, 0x2c, 0xa9, 0x09, 0x2f, 0x68, 0x09, 0x17, 0xad, 0x51, 0x1f, 0xad, 0xec, 0x91, 0xa5,
	0x3f, 0xe5, 0x12, 0xd2, 0x95, 0xdf, 0xb2, 0xec, 0xef, 0xbc, 0x90, 0x21, 0x0a, 0xd3, 0x23, 0x3b,
	0xab, 0x09, 0xa7, 0xb4, 0x82, 0xe2, 0x61, 0x23, 0xfd, 0x1a, 0xdb, 0x7d, 0xcf, 0xf2, 0x9a, 0xf0,
	0xaa, 0x29, 0x61, 0xd6, 0x89, 0x47, 0x8c, 0xcf, 0xe3, 0xdc, 0xbe, 0xbb, 0x25, 0xee, 0x1a, 0xfd,
	0xbf, 0x84, 0xe1, 0xc8, 0x25, 0x13, 0x37, 0x39, 0x76, 0xd3, 0x89, 0x9b, 0x4d, 0xdd, 0xc3, 0x2b,
	0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb5, 0xf5, 0x1f, 0xa9, 0x39, 0x01, 0x00, 0x00,
}
