// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ImageSvr.proto

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 查询资源列表请求
type STQueryStyleListReq struct {
	QueryBegin       *int32 `protobuf:"zigzag32,1,opt,name=QueryBegin" json:"QueryBegin,omitempty"`
	QueryNum         *int32 `protobuf:"zigzag32,2,opt,name=QueryNum" json:"QueryNum,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *STQueryStyleListReq) Reset()                    { *m = STQueryStyleListReq{} }
func (m *STQueryStyleListReq) String() string            { return proto.CompactTextString(m) }
func (*STQueryStyleListReq) ProtoMessage()               {}
func (*STQueryStyleListReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *STQueryStyleListReq) GetQueryBegin() int32 {
	if m != nil && m.QueryBegin != nil {
		return *m.QueryBegin
	}
	return 0
}

func (m *STQueryStyleListReq) GetQueryNum() int32 {
	if m != nil && m.QueryNum != nil {
		return *m.QueryNum
	}
	return 0
}

type STStyleInfo struct {
	StyleID          *int32             `protobuf:"zigzag32,1,opt,name=StyleID" json:"StyleID,omitempty"`
	StyleName        *string            `protobuf:"bytes,2,opt,name=StyleName" json:"StyleName,omitempty"`
	StyleType        *ERecommendTypeDef `protobuf:"varint,3,opt,name=StyleType,enum=client.ERecommendTypeDef" json:"StyleType,omitempty"`
	CreateTime       *int64             `protobuf:"zigzag64,4,opt,name=CreateTime" json:"CreateTime,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *STStyleInfo) Reset()                    { *m = STStyleInfo{} }
func (m *STStyleInfo) String() string            { return proto.CompactTextString(m) }
func (*STStyleInfo) ProtoMessage()               {}
func (*STStyleInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *STStyleInfo) GetStyleID() int32 {
	if m != nil && m.StyleID != nil {
		return *m.StyleID
	}
	return 0
}

func (m *STStyleInfo) GetStyleName() string {
	if m != nil && m.StyleName != nil {
		return *m.StyleName
	}
	return ""
}

func (m *STStyleInfo) GetStyleType() ERecommendTypeDef {
	if m != nil && m.StyleType != nil {
		return *m.StyleType
	}
	return ERecommendTypeDef_BANNER_TYPE
}

func (m *STStyleInfo) GetCreateTime() int64 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

// 查询资源列表响应
type STQueryStyleListRsp struct {
	StyleList        []*STStyleInfo `protobuf:"bytes,1,rep,name=StyleList" json:"StyleList,omitempty"`
	Total            *int32         `protobuf:"zigzag32,2,opt,name=Total" json:"Total,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *STQueryStyleListRsp) Reset()                    { *m = STQueryStyleListRsp{} }
func (m *STQueryStyleListRsp) String() string            { return proto.CompactTextString(m) }
func (*STQueryStyleListRsp) ProtoMessage()               {}
func (*STQueryStyleListRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *STQueryStyleListRsp) GetStyleList() []*STStyleInfo {
	if m != nil {
		return m.StyleList
	}
	return nil
}

func (m *STQueryStyleListRsp) GetTotal() int32 {
	if m != nil && m.Total != nil {
		return *m.Total
	}
	return 0
}

// 查询相册图片内容请求
type STQueryResourceListReq struct {
	StyleID          *int32 `protobuf:"zigzag32,1,opt,name=StyleID" json:"StyleID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *STQueryResourceListReq) Reset()                    { *m = STQueryResourceListReq{} }
func (m *STQueryResourceListReq) String() string            { return proto.CompactTextString(m) }
func (*STQueryResourceListReq) ProtoMessage()               {}
func (*STQueryResourceListReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func (m *STQueryResourceListReq) GetStyleID() int32 {
	if m != nil && m.StyleID != nil {
		return *m.StyleID
	}
	return 0
}

type STResourceImageInfo struct {
	ImageID          *int32  `protobuf:"zigzag32,1,opt,name=ImageID" json:"ImageID,omitempty"`
	Url              *string `protobuf:"bytes,2,opt,name=Url" json:"Url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STResourceImageInfo) Reset()                    { *m = STResourceImageInfo{} }
func (m *STResourceImageInfo) String() string            { return proto.CompactTextString(m) }
func (*STResourceImageInfo) ProtoMessage()               {}
func (*STResourceImageInfo) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{4} }

func (m *STResourceImageInfo) GetImageID() int32 {
	if m != nil && m.ImageID != nil {
		return *m.ImageID
	}
	return 0
}

func (m *STResourceImageInfo) GetUrl() string {
	if m != nil && m.Url != nil {
		return *m.Url
	}
	return ""
}

// 查询查询相册图片内容响应
type STQueryResourceListRsp struct {
	UrlList          []*STResourceImageInfo `protobuf:"bytes,1,rep,name=UrlList" json:"UrlList,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *STQueryResourceListRsp) Reset()                    { *m = STQueryResourceListRsp{} }
func (m *STQueryResourceListRsp) String() string            { return proto.CompactTextString(m) }
func (*STQueryResourceListRsp) ProtoMessage()               {}
func (*STQueryResourceListRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{5} }

func (m *STQueryResourceListRsp) GetUrlList() []*STResourceImageInfo {
	if m != nil {
		return m.UrlList
	}
	return nil
}

// 新建相册请求
type STCreateStyleReq struct {
	StyleName        *string            `protobuf:"bytes,1,opt,name=StyleName" json:"StyleName,omitempty"`
	StyleType        *ERecommendTypeDef `protobuf:"varint,2,opt,name=StyleType,enum=client.ERecommendTypeDef" json:"StyleType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *STCreateStyleReq) Reset()                    { *m = STCreateStyleReq{} }
func (m *STCreateStyleReq) String() string            { return proto.CompactTextString(m) }
func (*STCreateStyleReq) ProtoMessage()               {}
func (*STCreateStyleReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{6} }

func (m *STCreateStyleReq) GetStyleName() string {
	if m != nil && m.StyleName != nil {
		return *m.StyleName
	}
	return ""
}

func (m *STCreateStyleReq) GetStyleType() ERecommendTypeDef {
	if m != nil && m.StyleType != nil {
		return *m.StyleType
	}
	return ERecommendTypeDef_BANNER_TYPE
}

// 新建相册响应
type STCreateStyleRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STCreateStyleRsp) Reset()                    { *m = STCreateStyleRsp{} }
func (m *STCreateStyleRsp) String() string            { return proto.CompactTextString(m) }
func (*STCreateStyleRsp) ProtoMessage()               {}
func (*STCreateStyleRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{7} }

// 上传图片请求
type STUploadImageReq struct {
	StyleID          *int32  `protobuf:"zigzag32,1,opt,name=StyleID" json:"StyleID,omitempty"`
	Image            *string `protobuf:"bytes,2,opt,name=Image" json:"Image,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STUploadImageReq) Reset()                    { *m = STUploadImageReq{} }
func (m *STUploadImageReq) String() string            { return proto.CompactTextString(m) }
func (*STUploadImageReq) ProtoMessage()               {}
func (*STUploadImageReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{8} }

func (m *STUploadImageReq) GetStyleID() int32 {
	if m != nil && m.StyleID != nil {
		return *m.StyleID
	}
	return 0
}

func (m *STUploadImageReq) GetImage() string {
	if m != nil && m.Image != nil {
		return *m.Image
	}
	return ""
}

// 上传图片请求
type STUploadImageRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STUploadImageRsp) Reset()                    { *m = STUploadImageRsp{} }
func (m *STUploadImageRsp) String() string            { return proto.CompactTextString(m) }
func (*STUploadImageRsp) ProtoMessage()               {}
func (*STUploadImageRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{9} }

// 删除相册请求
type STDeleteStyleReq struct {
	StyleID          *int32 `protobuf:"zigzag32,1,opt,name=StyleID" json:"StyleID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *STDeleteStyleReq) Reset()                    { *m = STDeleteStyleReq{} }
func (m *STDeleteStyleReq) String() string            { return proto.CompactTextString(m) }
func (*STDeleteStyleReq) ProtoMessage()               {}
func (*STDeleteStyleReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{10} }

func (m *STDeleteStyleReq) GetStyleID() int32 {
	if m != nil && m.StyleID != nil {
		return *m.StyleID
	}
	return 0
}

// 删除相册响应
type STDeleteStyleRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STDeleteStyleRsp) Reset()                    { *m = STDeleteStyleRsp{} }
func (m *STDeleteStyleRsp) String() string            { return proto.CompactTextString(m) }
func (*STDeleteStyleRsp) ProtoMessage()               {}
func (*STDeleteStyleRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{11} }

// 删除图片资源请求
type STDeleteResourceReq struct {
	ImageID          *int32 `protobuf:"zigzag32,1,opt,name=ImageID" json:"ImageID,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *STDeleteResourceReq) Reset()                    { *m = STDeleteResourceReq{} }
func (m *STDeleteResourceReq) String() string            { return proto.CompactTextString(m) }
func (*STDeleteResourceReq) ProtoMessage()               {}
func (*STDeleteResourceReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{12} }

func (m *STDeleteResourceReq) GetImageID() int32 {
	if m != nil && m.ImageID != nil {
		return *m.ImageID
	}
	return 0
}

// 删除图片资源响应
type STDeleteResourceRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STDeleteResourceRsp) Reset()                    { *m = STDeleteResourceRsp{} }
func (m *STDeleteResourceRsp) String() string            { return proto.CompactTextString(m) }
func (*STDeleteResourceRsp) ProtoMessage()               {}
func (*STDeleteResourceRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{13} }

// 编辑相册资源请求
type STUpdateStyleReq struct {
	StyleID          *int32             `protobuf:"zigzag32,1,req,name=StyleID" json:"StyleID,omitempty"`
	StyleName        *string            `protobuf:"bytes,2,opt,name=StyleName" json:"StyleName,omitempty"`
	StyleType        *ERecommendTypeDef `protobuf:"varint,3,opt,name=StyleType,enum=client.ERecommendTypeDef" json:"StyleType,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *STUpdateStyleReq) Reset()                    { *m = STUpdateStyleReq{} }
func (m *STUpdateStyleReq) String() string            { return proto.CompactTextString(m) }
func (*STUpdateStyleReq) ProtoMessage()               {}
func (*STUpdateStyleReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{14} }

func (m *STUpdateStyleReq) GetStyleID() int32 {
	if m != nil && m.StyleID != nil {
		return *m.StyleID
	}
	return 0
}

func (m *STUpdateStyleReq) GetStyleName() string {
	if m != nil && m.StyleName != nil {
		return *m.StyleName
	}
	return ""
}

func (m *STUpdateStyleReq) GetStyleType() ERecommendTypeDef {
	if m != nil && m.StyleType != nil {
		return *m.StyleType
	}
	return ERecommendTypeDef_BANNER_TYPE
}

// 编辑相册资源响应
type STUpdateStyleRsp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *STUpdateStyleRsp) Reset()                    { *m = STUpdateStyleRsp{} }
func (m *STUpdateStyleRsp) String() string            { return proto.CompactTextString(m) }
func (*STUpdateStyleRsp) ProtoMessage()               {}
func (*STUpdateStyleRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{15} }

func init() {
	proto.RegisterType((*STQueryStyleListReq)(nil), "client.STQueryStyleListReq")
	proto.RegisterType((*STStyleInfo)(nil), "client.STStyleInfo")
	proto.RegisterType((*STQueryStyleListRsp)(nil), "client.STQueryStyleListRsp")
	proto.RegisterType((*STQueryResourceListReq)(nil), "client.STQueryResourceListReq")
	proto.RegisterType((*STResourceImageInfo)(nil), "client.STResourceImageInfo")
	proto.RegisterType((*STQueryResourceListRsp)(nil), "client.STQueryResourceListRsp")
	proto.RegisterType((*STCreateStyleReq)(nil), "client.STCreateStyleReq")
	proto.RegisterType((*STCreateStyleRsp)(nil), "client.STCreateStyleRsp")
	proto.RegisterType((*STUploadImageReq)(nil), "client.STUploadImageReq")
	proto.RegisterType((*STUploadImageRsp)(nil), "client.STUploadImageRsp")
	proto.RegisterType((*STDeleteStyleReq)(nil), "client.STDeleteStyleReq")
	proto.RegisterType((*STDeleteStyleRsp)(nil), "client.STDeleteStyleRsp")
	proto.RegisterType((*STDeleteResourceReq)(nil), "client.STDeleteResourceReq")
	proto.RegisterType((*STDeleteResourceRsp)(nil), "client.STDeleteResourceRsp")
	proto.RegisterType((*STUpdateStyleReq)(nil), "client.STUpdateStyleReq")
	proto.RegisterType((*STUpdateStyleRsp)(nil), "client.STUpdateStyleRsp")
}

func init() { proto.RegisterFile("ImageSvr.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x5f, 0x4f, 0xf2, 0x30,
	0x18, 0xc5, 0x33, 0x78, 0x5f, 0x91, 0x12, 0x11, 0x8a, 0x9a, 0xa9, 0x37, 0x4b, 0x4d, 0xc8, 0x4c,
	0x08, 0x17, 0x78, 0xe9, 0x9d, 0xa0, 0x09, 0x09, 0x21, 0xca, 0xc6, 0x07, 0x58, 0xb6, 0x07, 0xb2,
	0x64, 0x5d, 0xeb, 0x3a, 0x4c, 0xf8, 0xf6, 0xa6, 0x7f, 0xa6, 0x63, 0xcc, 0x78, 0xe3, 0x65, 0x4f,
	0xfb, 0x9c, 0xe7, 0x9c, 0x5f, 0x8a, 0xba, 0x73, 0x1a, 0x6c, 0xc1, 0xfb, 0xc8, 0xc6, 0x3c, 0x63,
	0x39, 0xc3, 0x27, 0x61, 0x12, 0x43, 0x9a, 0xdf, 0x5c, 0x4c, 0x19, 0xa5, 0x2c, 0x7d, 0x95, 0x62,
	0xc8, 0x12, 0x7d, 0x4b, 0x1e, 0xd1, 0xc0, 0xf3, 0xdf, 0x76, 0x90, 0xed, 0xbd, 0x7c, 0x9f, 0xc0,
	0x22, 0x16, 0xf9, 0x0a, 0xde, 0x31, 0x46, 0x48, 0x89, 0x4f, 0xb0, 0x8d, 0x53, 0xdb, 0x72, 0x2c,
	0xb7, 0x8f, 0x7b, 0xe8, 0x54, 0x69, 0xcb, 0x1d, 0xb5, 0x1b, 0x52, 0x21, 0x02, 0x75, 0x3c, 0x5f,
	0xcd, 0xcd, 0xd3, 0x0d, 0xc3, 0xe7, 0xa8, 0xa5, 0x0f, 0x33, 0x33, 0xd1, 0x47, 0x6d, 0x25, 0x2c,
	0x03, 0x0a, 0x6a, 0xa4, 0x8d, 0x47, 0x46, 0xf2, 0xf7, 0x1c, 0xec, 0xa6, 0x63, 0xb9, 0xdd, 0xc9,
	0xf5, 0x58, 0x27, 0x1c, 0x3f, 0xaf, 0x20, 0x64, 0x94, 0x42, 0x1a, 0xc9, 0xdb, 0x19, 0x6c, 0x64,
	0x8c, 0x69, 0x06, 0x41, 0x0e, 0x7e, 0x4c, 0xc1, 0xfe, 0xe7, 0x58, 0x2e, 0x26, 0x8b, 0x9a, 0xc4,
	0x82, 0xe3, 0xa1, 0x31, 0x96, 0x67, 0xdb, 0x72, 0x9a, 0x6e, 0x67, 0x32, 0x28, 0x8c, 0xcb, 0x21,
	0xcf, 0xd0, 0x7f, 0x9f, 0xe5, 0x41, 0x62, 0x2a, 0xdc, 0xa3, 0x2b, 0xe3, 0xb6, 0x02, 0xc1, 0x76,
	0x59, 0xf8, 0x85, 0xa0, 0xda, 0x86, 0x3c, 0xc8, 0xc5, 0xc5, 0x2b, 0x05, 0xb9, 0x68, 0xad, 0x0f,
	0x45, 0xeb, 0x0e, 0x6a, 0xae, 0x33, 0xed, 0xdf, 0x26, 0x2f, 0xf5, 0xfe, 0x82, 0xe3, 0x11, 0x6a,
	0xad, 0xb3, 0xa4, 0x14, 0xf7, 0xf6, 0x3b, 0xee, 0xd1, 0x16, 0xe2, 0xa1, 0x9e, 0xe7, 0x6b, 0x16,
	0x2a, 0x95, 0x4c, 0x78, 0x80, 0xd7, 0x3a, 0xc6, 0xdb, 0xf8, 0x05, 0x2f, 0xc1, 0x55, 0x53, 0xc1,
	0xc9, 0x44, 0x6a, 0x6b, 0x9e, 0xb0, 0x20, 0x52, 0xdb, 0xeb, 0x50, 0x48, 0x88, 0xea, 0xd2, 0x94,
	0xc4, 0xd5, 0x19, 0xc1, 0xc9, 0x9d, 0xd4, 0x66, 0x90, 0x40, 0x29, 0xf0, 0x11, 0x52, 0x5c, 0x7d,
	0x24, 0x38, 0x19, 0x4a, 0xcc, 0x5a, 0x2b, 0x30, 0x98, 0xd9, 0x03, 0xcc, 0xe4, 0xb2, 0xe6, 0x9d,
	0xe0, 0x24, 0xd2, 0x59, 0xa2, 0xe0, 0xa7, 0xbd, 0x8d, 0x3f, 0xf8, 0x98, 0x45, 0xe3, 0xa8, 0x44,
	0xee, 0x33, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xf6, 0x96, 0xde, 0x79, 0x03, 0x00, 0x00,
}
