/*
 * Auto generated by code_generator
 * Please do not modify it.
 */
package client

import (
	//"github.com/astaxie/beego"
	"github.com/golang/protobuf/proto"
	"showgirl/models/utils"
)

type ImageClient struct {
	CommonClient
}


func (this *ImageClient) QueryStyleList(hdr *STUserTrustInfo, req *STQueryStyleListReq, header map[string]string) (*STRspHeader, *STQueryStyleListRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient QueryStyleList Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/QueryStyleList", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image QueryStyleList bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STQueryStyleListRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient QueryStyleList Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *ImageClient) QueryResourceList(hdr *STUserTrustInfo, req *STQueryResourceListReq, header map[string]string) (*STRspHeader, *STQueryResourceListRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient QueryResourceList Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/QueryResourceList", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image QueryResourceList bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STQueryResourceListRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient QueryResourceList Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *ImageClient) CreateStyle(hdr *STUserTrustInfo, req *STCreateStyleReq, header map[string]string) (*STRspHeader, *STCreateStyleRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient CreateStyle Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/CreateStyle", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image CreateStyle bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STCreateStyleRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient CreateStyle Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *ImageClient) UploadImage(hdr *STUserTrustInfo, req *STUploadImageReq, header map[string]string) (*STRspHeader, *STUploadImageRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient UploadImage Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/UploadImage", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image UploadImage bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STUploadImageRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient UploadImage Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *ImageClient) DeleteStyle(hdr *STUserTrustInfo, req *STDeleteStyleReq, header map[string]string) (*STRspHeader, *STDeleteStyleRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient DeleteStyle Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/DeleteStyle", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image DeleteStyle bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STDeleteStyleRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient DeleteStyle Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

func (this *ImageClient) DeleteResource(hdr *STUserTrustInfo, req *STDeleteResourceReq, header map[string]string) (*STRspHeader, *STDeleteResourceRsp, error) {

	utils.Debug(hdr.GetFlowId(), "ImageClient DeleteResource Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("Image", "/Image/DeleteResource", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request Image DeleteResource bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &STDeleteResourceRsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "ImageClient DeleteResource Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}

