// Code generated by protoc-gen-go. DO NOT EDIT.
// source: PaySvr.proto

package client

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// 创建微信支付订单请求
type STCreateTransactionReq struct {
	GoodsDesc        *string `protobuf:"bytes,1,opt,name=GoodsDesc" json:"GoodsDesc,omitempty"`
	GoodsDetail      *string `protobuf:"bytes,2,opt,name=GoodsDetail" json:"GoodsDetail,omitempty"`
	FeeAmount        *int32  `protobuf:"zigzag32,3,opt,name=FeeAmount" json:"FeeAmount,omitempty"`
	OpenID           *string `protobuf:"bytes,4,opt,name=OpenID" json:"OpenID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STCreateTransactionReq) Reset()                    { *m = STCreateTransactionReq{} }
func (m *STCreateTransactionReq) String() string            { return proto.CompactTextString(m) }
func (*STCreateTransactionReq) ProtoMessage()               {}
func (*STCreateTransactionReq) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *STCreateTransactionReq) GetGoodsDesc() string {
	if m != nil && m.GoodsDesc != nil {
		return *m.GoodsDesc
	}
	return ""
}

func (m *STCreateTransactionReq) GetGoodsDetail() string {
	if m != nil && m.GoodsDetail != nil {
		return *m.GoodsDetail
	}
	return ""
}

func (m *STCreateTransactionReq) GetFeeAmount() int32 {
	if m != nil && m.FeeAmount != nil {
		return *m.FeeAmount
	}
	return 0
}

func (m *STCreateTransactionReq) GetOpenID() string {
	if m != nil && m.OpenID != nil {
		return *m.OpenID
	}
	return ""
}

// 创建微信支付订单响应
type STCreateTransactionRsp struct {
	AppId            *string `protobuf:"bytes,1,opt,name=AppId" json:"AppId,omitempty"`
	MchID            *string `protobuf:"bytes,2,opt,name=MchID" json:"MchID,omitempty"`
	DeviceInfo       *string `protobuf:"bytes,3,opt,name=DeviceInfo" json:"DeviceInfo,omitempty"`
	NonceStr         *string `protobuf:"bytes,4,opt,name=NonceStr" json:"NonceStr,omitempty"`
	Sign             *string `protobuf:"bytes,5,opt,name=Sign" json:"Sign,omitempty"`
	ResultCode       *string `protobuf:"bytes,6,opt,name=ResultCode" json:"ResultCode,omitempty"`
	ErrCode          *string `protobuf:"bytes,7,opt,name=ErrCode" json:"ErrCode,omitempty"`
	ErrCodeDes       *string `protobuf:"bytes,8,opt,name=ErrCodeDes" json:"ErrCodeDes,omitempty"`
	TradeType        *string `protobuf:"bytes,9,opt,name=TradeType" json:"TradeType,omitempty"`
	PrepayID         *string `protobuf:"bytes,10,opt,name=PrepayID" json:"PrepayID,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *STCreateTransactionRsp) Reset()                    { *m = STCreateTransactionRsp{} }
func (m *STCreateTransactionRsp) String() string            { return proto.CompactTextString(m) }
func (*STCreateTransactionRsp) ProtoMessage()               {}
func (*STCreateTransactionRsp) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *STCreateTransactionRsp) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *STCreateTransactionRsp) GetMchID() string {
	if m != nil && m.MchID != nil {
		return *m.MchID
	}
	return ""
}

func (m *STCreateTransactionRsp) GetDeviceInfo() string {
	if m != nil && m.DeviceInfo != nil {
		return *m.DeviceInfo
	}
	return ""
}

func (m *STCreateTransactionRsp) GetNonceStr() string {
	if m != nil && m.NonceStr != nil {
		return *m.NonceStr
	}
	return ""
}

func (m *STCreateTransactionRsp) GetSign() string {
	if m != nil && m.Sign != nil {
		return *m.Sign
	}
	return ""
}

func (m *STCreateTransactionRsp) GetResultCode() string {
	if m != nil && m.ResultCode != nil {
		return *m.ResultCode
	}
	return ""
}

func (m *STCreateTransactionRsp) GetErrCode() string {
	if m != nil && m.ErrCode != nil {
		return *m.ErrCode
	}
	return ""
}

func (m *STCreateTransactionRsp) GetErrCodeDes() string {
	if m != nil && m.ErrCodeDes != nil {
		return *m.ErrCodeDes
	}
	return ""
}

func (m *STCreateTransactionRsp) GetTradeType() string {
	if m != nil && m.TradeType != nil {
		return *m.TradeType
	}
	return ""
}

func (m *STCreateTransactionRsp) GetPrepayID() string {
	if m != nil && m.PrepayID != nil {
		return *m.PrepayID
	}
	return ""
}

func init() {
	proto.RegisterType((*STCreateTransactionReq)(nil), "client.STCreateTransactionReq")
	proto.RegisterType((*STCreateTransactionRsp)(nil), "client.STCreateTransactionRsp")
}

func init() { proto.RegisterFile("PaySvr.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0xcf, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x05, 0x50, 0x05, 0x9a, 0xb4, 0x1e, 0x5a, 0x20, 0x46, 0x42, 0x5e, 0x56, 0x5d, 0x75, 0xc5,
	0x1d, 0xaa, 0x1a, 0x90, 0x17, 0x40, 0xd5, 0xe4, 0x02, 0x96, 0x33, 0x80, 0xa5, 0x60, 0x9b, 0xb1,
	0x5b, 0x29, 0x37, 0xe4, 0x58, 0x28, 0x21, 0xd9, 0xb1, 0x7d, 0xfa, 0xf3, 0xbf, 0x06, 0x96, 0x07,
	0xdd, 0x55, 0x67, 0x7a, 0x08, 0xe4, 0x93, 0xe7, 0x85, 0x69, 0x2d, 0xba, 0xb4, 0x31, 0x70, 0x5f,
	0xd5, 0x7b, 0x42, 0x9d, 0xb0, 0x26, 0xed, 0xa2, 0x36, 0xc9, 0x7a, 0x77, 0xc4, 0x6f, 0x5e, 0x02,
	0x7b, 0xf6, 0xbe, 0x89, 0x12, 0xa3, 0x11, 0xd9, 0x3a, 0xdb, 0x32, 0x7e, 0x07, 0x57, 0x23, 0x25,
	0x6d, 0x5b, 0x71, 0x31, 0x60, 0x09, 0xec, 0x09, 0x71, 0xf7, 0xe5, 0x4f, 0x2e, 0x89, 0xcb, 0x75,
	0xb6, 0x2d, 0xf9, 0x35, 0x14, 0x6f, 0x01, 0x9d, 0x92, 0x62, 0xd6, 0x47, 0x36, 0x3f, 0xd9, 0xff,
	0x2b, 0x31, 0xf0, 0x15, 0xe4, 0xbb, 0x10, 0x54, 0x33, 0x2e, 0xac, 0x20, 0x7f, 0x31, 0x9f, 0x4a,
	0x8e, 0xdd, 0x1c, 0x40, 0xe2, 0xd9, 0x1a, 0x54, 0xee, 0xdd, 0x0f, 0xe5, 0x8c, 0xdf, 0xc2, 0xe2,
	0xd5, 0x3b, 0x83, 0x55, 0xa2, 0xbf, 0x7a, 0xbe, 0x84, 0x59, 0x65, 0x3f, 0x9c, 0xc8, 0xa7, 0x9b,
	0x23, 0xc6, 0x53, 0x9b, 0xf6, 0xbe, 0x41, 0x51, 0x0c, 0x76, 0x03, 0xf3, 0x47, 0xa2, 0x01, 0xe6,
	0x53, 0x68, 0x04, 0x89, 0x51, 0x2c, 0xa6, 0x47, 0x6a, 0xd2, 0x0d, 0xd6, 0x5d, 0x40, 0xc1, 0xa6,
	0xad, 0x03, 0x61, 0xd0, 0x9d, 0x92, 0x02, 0x7a, 0xf9, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xf6, 0xd8,
	0x16, 0x73, 0x46, 0x01, 0x00, 0x00,
}
