/*
 * Auto generated by code_generator
 * Please do not modify it.
 */
package {{.pkg}}

import (
	//"github.com/astaxie/beego"
	"github.com/golang/protobuf/proto"
	"showgirl/models/utils"
)

type {{.module}}Client struct {
	CommonClient
}

{{range $key, $method := .methods}}
func (this *{{$.module}}Client) {{$method}}(hdr *STUserTrustInfo, req *ST{{$method}}Req, header map[string]string) (*STRspHeader, *ST{{$method}}Rsp, error) {

	utils.Debug(hdr.GetFlowId(), "{{$.module}}Client {{$method}} Request debug, reqHeader = %s, reqInfo = %s", hdr.String(), req.String())

	reqData, err := proto.Marshal(req)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commReq := &CommonReq {
		UserTrustInfo: hdr,
		ReqInfo      : reqData,
	}

	data, err := proto.Marshal(commReq)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_MARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	body, err := this.Call("{{$.module}}", "/{{$.module}}/{{$method}}", data, header, hdr.GetFlowId())
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_CALL_FAILED_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	commonRes := &CommonRsp{}

	bodyLen := len(body)
	utils.Debug(hdr.GetFlowId(), "client Request {{$.module}} {{$method}} bodyLen = %d, body = %x", bodyLen, body)

	err = proto.Unmarshal(body, commonRes)
	if err != nil {
		utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
		return nil, nil, err
	}

	rspHeader := commonRes.RspHeader

	rspInfo := &ST{{$method}}Rsp{}
	if len(commonRes.RspInfo) > 0{
		err = proto.Unmarshal(commonRes.RspInfo, rspInfo)
		if err != nil {
			utils.Warn(hdr.GetFlowId(), RPC_UNMARSHAL_ABNORMAL_PREFIX+" = %s", err.Error())
			return nil, nil, err
		}
	}
	
	utils.Debug(hdr.GetFlowId(), "{{$.module}}Client {{$method}} Response debug, rspHeader = %s, rspInfo = %s", rspHeader.String(), rspInfo.String())

	return rspHeader, rspInfo, nil
}
{{end}}
