/*
 * Auto generated by client.python
 * Please do not modify it.
 */
package routers

import (
	"github.com/astaxie/beego"
	"os"
	"strings"
	"showgirl/controllers"
)

func init() {
	moduleStr := beego.AppConfig.String("module")
	modules := strings.Split(moduleStr, ",")
	for _, m := range modules {
		switch m {
		{{range $module, $methods := .modules}}
		case "{{$module}}":{{range $key, $method := $methods}}
			beego.Router("/{{$module | lowerCase}}/{{$method | lowerCase}}", &controllers.{{$module}}Controller{}, "post:{{$method}}")
		{{end}}{{end}}
		case "GoFront":
		{{range $module, $methods := .publics}}{{range $key, $v := $methods}}
			beego.Router("/v1.0/{{$module | lowerCase}}/{{$v.MethodName | lowerCase}}", &controllers.GoFrontController{}, "post:{{$module}}_{{$v.MethodName}}")
		{{end}}{{end}}
		case "OpGateway":
		{{range $module, $methods := .modules}}{{range $key, $method := $methods}}
			beego.Router("/op/{{$module | lowerCase}}/{{$method | lowerCase}}", &controllers.OpGatewayController{}, "post:{{$module}}_{{$method}}")
		{{end}}{{end}}
		default:
			beego.BeeLogger.Critical("Unknown module. module:%s", m)
			os.Exit(1)
		}
	}

}
